name: Bug Report Form
description: File a bug report
labels: ["bug"]
assignees:
  - SanAndreaP
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "Windows 10 21H2"
    validations:
      required: true  
  - type: input
    id: Terraria
    attributes:
      label: Terraria Version
      description: "Please provide the full Terraria version."
      placeholder: "v1.4.3.6"
    validations:
      required: true
  - type: input
    id: tModLoader
    attributes:
      label: tModLoader Version
      description: "Please provide the full tModLoader version."
      placeholder: "v2022.8.54.6"
    validations:
      required: true
  - type: input
    id: modVer
    attributes:
      label: DeMossifier Version
      description: "Please provide the version of this mod you're using."
      placeholder: "v1.3"
    validations:
      required: true
  - type: dropdown
    id: spmp
    attributes:
      label: Single- or Multiplayer
      description: "Is this bug happening on single- or multiplayer?"
      multiple: false
      options:
        - Singleplayer
        - Multiplayer
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: client.log output
      description: "Provide the contents of the client.log file (found in `[SteamLocation]/steamapps/common/tModLoader/tModLoader-Logs/`). No need for backticks here."
      render: shell
    validations:
      required: true
  - type: textarea
    id: crashlogs
    attributes:
      label: Relevant log output
      description: "If applicable, provide the contents of the client-crashlog.txt file (found in `[SteamLocation]/steamapps/common/tModLoader/`). No need for backticks here."
      render: shell
  - type: textarea
    id: files
    attributes:
      label: Additional files
      description: "Do you have additional files you want to provide, like screenshots? Unfortunately, as of now, these forms do not support file upload. So you need to upload them yourself somewhere and paste the link(s) here."
      render: shell
